In [138]:
import pandas as pd

In [139]:
data = pd.read_csv('./Crime_2020-2026_untransformed.csv')

# Data Exloration

In [140]:
data.dtypes

ID                        int64
Case Number                 str
Date                        str
Block                       str
IUCR                        str
Primary Type                str
Description                 str
Location Description        str
Arrest                     bool
Domestic                   bool
Beat                      int64
District                  int64
Ward                    float64
Community Area          float64
FBI Code                    str
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Updated On                  str
Latitude                float64
Longitude               float64
Location                    str
dtype: object

In [141]:
data['Primary Type'].unique() # all crime types

<StringArray>
[                  'CRIMINAL DAMAGE',                             'ARSON',
                          'BURGLARY',                'DECEPTIVE PRACTICE',
                             'THEFT',                     'OTHER OFFENSE',
               'MOTOR VEHICLE THEFT',  'INTERFERENCE WITH PUBLIC OFFICER',
                           'BATTERY',                         'NARCOTICS',
                 'WEAPONS VIOLATION',                           'ASSAULT',
                           'ROBBERY',            'PUBLIC PEACE VIOLATION',
                       'SEX OFFENSE',                 'CRIMINAL TRESPASS',
                          'STALKING',           'CRIMINAL SEXUAL ASSAULT',
 'CONCEALED CARRY LICENSE VIOLATION',                      'INTIMIDATION',
        'OFFENSE INVOLVING CHILDREN',                          'HOMICIDE',
                        'KIDNAPPING',              'LIQUOR LAW VIOLATION',
                         'OBSCENITY',          'OTHER NARCOTIC VIOLATION',
                      'NON-CRIMINAL',                          'GAMBLING',
                      'PROSTITUTION',                  'PUBLIC INDECENCY',
                 'HUMAN TRAFFICKING',                         'RITUALISM',
               'CRIM SEXUAL ASSAULT']
Length: 33, dtype: str

In [142]:
data['Primary Type'].value_counts() # number of records per crime type

Primary Type
THEFT                                348788
BATTERY                              289051
CRIMINAL DAMAGE                      181640
ASSAULT                              143318
MOTOR VEHICLE THEFT                  124225
DECEPTIVE PRACTICE                   113624
OTHER OFFENSE                        102943
BURGLARY                              59400
ROBBERY                               54394
WEAPONS VIOLATION                     52039
NARCOTICS                             41560
CRIMINAL TRESPASS                     31045
OFFENSE INVOLVING CHILDREN            12654
CRIMINAL SEXUAL ASSAULT               11392
SEX OFFENSE                            8720
PUBLIC PEACE VIOLATION                 6513
HOMICIDE                               4357
INTERFERENCE WITH PUBLIC OFFICER       4355
ARSON                                  3201
STALKING                               3162
PROSTITUTION                           1468
CONCEALED CARRY LICENSE VIOLATION      1375
LIQUOR LAW VIOLATION                   1284
INTIMIDATION                           1209
KIDNAPPING                              742
OBSCENITY                               360
HUMAN TRAFFICKING                       117
GAMBLING                                111
CRIM SEXUAL ASSAULT                      77
PUBLIC INDECENCY                         61
OTHER NARCOTIC VIOLATION                 38
NON-CRIMINAL                             24
RITUALISM                                 1
Name: count, dtype: int64

In [143]:
data['Location Description'].value_counts() # number of crimes at each location

Location Description
STREET                                    429828
APARTMENT                                 307692
RESIDENCE                                 215297
SIDEWALK                                   85561
PARKING LOT / GARAGE (NON RESIDENTIAL)     54036
                                           ...
BANQUET HALL                                   1
TRUCK                                          1
ELEVATOR                                       1
CHA ELEVATOR                                   1
NURSING HOME                                   1
Name: count, Length: 183, dtype: int64

In [144]:
data.groupby('Primary Type')['Arrest'].sum().sort_values(ascending=False) # Number of arrests per crime type

Primary Type
BATTERY                              48132
NARCOTICS                            40537
WEAPONS VIOLATION                    33468
THEFT                                21809
OTHER OFFENSE                        16575
ASSAULT                              15920
CRIMINAL TRESPASS                     9787
CRIMINAL DAMAGE                       7048
MOTOR VEHICLE THEFT                   3978
ROBBERY                               3972
INTERFERENCE WITH PUBLIC OFFICER      3868
PUBLIC PEACE VIOLATION                3005
DECEPTIVE PRACTICE                    2938
BURGLARY                              2904
HOMICIDE                              1773
PROSTITUTION                          1417
CONCEALED CARRY LICENSE VIOLATION     1318
LIQUOR LAW VIOLATION                  1249
OFFENSE INVOLVING CHILDREN            1209
SEX OFFENSE                            753
CRIMINAL SEXUAL ASSAULT                577
ARSON                                  301
OBSCENITY                              207
STALKING                               189
GAMBLING                               108
PUBLIC INDECENCY                        56
KIDNAPPING                              52
INTIMIDATION                            28
OTHER NARCOTIC VIOLATION                19
NON-CRIMINAL                             7
HUMAN TRAFFICKING                        4
CRIM SEXUAL ASSAULT                      3
RITUALISM                                0
Name: Arrest, dtype: int64

# Data Transformation

## Remove Unwanted Columns

In [145]:
data = data.drop(columns=['Block', 'IUCR', 'Description', 'Domestic', 'Beat', 'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate', 'Y Coordinate', 'Updated On', 'Latitude', 'Longitude', 'Location'])

data

,ID,Case Number,Date,Primary Type,Location Description,Arrest,Year
0,14354393,JK445985,10/06/2026 12:00:00 AM,CRIMINAL DAMAGE,STREET,False,2026
1,14350659,JK441321,10/06/2026 12:00:00 AM,ARSON,POLICE FACILITY / VEHICLE PARKING LOT,False,2026
2,14349733,JK440247,10/06/2026 12:00:00 AM,BURGLARY,STREET,False,2026
3,14350574,JK440996,10/06/2026 12:00:00 AM,DECEPTIVE PRACTICE,APARTMENT,False,2026
4,14351522,JK442283,10/06/2026 12:00:00 AM,CRIMINAL DAMAGE,STREET,False,2026
...,...,...,...,...,...,...,...
1603243,12470647,JE359306,01/01/2020 12:00:00 AM,DECEPTIVE PRACTICE,RESIDENCE,False,2020
1603244,12522374,JE422429,01/01/2020 12:00:00 AM,CRIMINAL SEXUAL ASSAULT,RESIDENCE,False,2020
1603245,13549608,JH368327,01/01/2020 12:00:00 AM,OFFENSE INVOLVING CHILDREN,RESIDENCE,False,2020
1603246,12578771,JE490784,01/01/2020 12:00:00 AM,DECEPTIVE PRACTICE,RESIDENCE,False,2020
1603247,12542772,JE447428,01/01/2020 12:00:00 AM,DECEPTIVE PRACTICE,OTHER (SPECIFY),False,2020

## Rename Column

In [146]:
data.rename(columns={'Location Description': 'Location', 'Primary Type': 'Crime Type'}, inplace=True)
data

,ID,Case Number,Date,Crime Type,Location,Arrest,Year
0,14354393,JK445985,10/06/2026 12:00:00 AM,CRIMINAL DAMAGE,STREET,False,2026
1,14350659,JK441321,10/06/2026 12:00:00 AM,ARSON,POLICE FACILITY / VEHICLE PARKING LOT,False,2026
2,14349733,JK440247,10/06/2026 12:00:00 AM,BURGLARY,STREET,False,2026
3,14350574,JK440996,10/06/2026 12:00:00 AM,DECEPTIVE PRACTICE,APARTMENT,False,2026
4,14351522,JK442283,10/06/2026 12:00:00 AM,CRIMINAL DAMAGE,STREET,False,2026
...,...,...,...,...,...,...,...
1603243,12470647,JE359306,01/01/2020 12:00:00 AM,DECEPTIVE PRACTICE,RESIDENCE,False,2020
1603244,12522374,JE422429,01/01/2020 12:00:00 AM,CRIMINAL SEXUAL ASSAULT,RESIDENCE,False,2020
1603245,13549608,JH368327,01/01/2020 12:00:00 AM,OFFENSE INVOLVING CHILDREN,RESIDENCE,False,2020
1603246,12578771,JE490784,01/01/2020 12:00:00 AM,DECEPTIVE PRACTICE,RESIDENCE,False,2020
1603247,12542772,JE447428,01/01/2020 12:00:00 AM,DECEPTIVE PRACTICE,OTHER (SPECIFY),False,2020

## Split Date Column

In [147]:
# Format: month/day/year hour:minute:second AM/PM (e.g., 10/06/2026 12:00:00 AM)
data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y %I:%M:%S %p', errors='coerce')

data['Month'] = data['Date'].dt.month
data['Day'] = data['Date'].dt.day
data['Year'] = data['Date'].dt.year

data['Time'] = data['Date'].dt.strftime('%I:%M %p') # 12 hour clock

data[['Month', 'Day', 'Year', 'Time']]

         Month  Day  Year      Time
0           10    6  2026  12:00 AM
1           10    6  2026  12:00 AM
2           10    6  2026  12:00 AM
3           10    6  2026  12:00 AM
4           10    6  2026  12:00 AM
...        ...  ...   ...       ...
1603243      1    1  2020  12:00 AM
1603244      1    1  2020  12:00 AM
1603245      1    1  2020  12:00 AM
1603246      1    1  2020  12:00 AM
1603247      1    1  2020  12:00 AM

[1603248 rows x 4 columns]

## Arrest Rate

In [148]:
data['Arrest Rate'] = data.groupby('Crime Type')['Arrest'].transform('mean')*100 # arrest rate (percentage)

data[['Crime Type', 'Arrest Rate']].drop_duplicates(subset='Crime Type').sort_values('Arrest Rate', ascending=False) # arrest rates by crime descending order

                                Crime Type  Arrest Rate
17                               NARCOTICS    97.538499
8208                              GAMBLING    97.297297
3204                  LIQUOR LAW VIOLATION    97.274143
8537                          PROSTITUTION    96.525886
230      CONCEALED CARRY LICENSE VIOLATION    95.854545
14755                     PUBLIC INDECENCY    91.803279
10        INTERFERENCE WITH PUBLIC OFFICER    88.817451
23                       WEAPONS VIOLATION    64.313303
3476                             OBSCENITY    57.500000
6821              OTHER NARCOTIC VIOLATION    50.000000
51                  PUBLIC PEACE VIOLATION    46.138492
1588                              HOMICIDE    40.693137
67                       CRIMINAL TRESPASS    31.525205
7566                          NON-CRIMINAL    29.166667
11                                 BATTERY    16.651733
7                            OTHER OFFENSE    16.101143
24                                 ASSAULT    11.108165
834             OFFENSE INVOLVING CHILDREN     9.554291
1                                    ARSON     9.403311
61                             SEX OFFENSE     8.635321
32                                 ROBBERY     7.302276
2114                            KIDNAPPING     7.008086
5                                    THEFT     6.252795
79                                STALKING     5.977230
216                CRIMINAL SEXUAL ASSAULT     5.064958
2                                 BURGLARY     4.888889
1569792                CRIM SEXUAL ASSAULT     3.896104
0                          CRIMINAL DAMAGE     3.880203
19784                    HUMAN TRAFFICKING     3.418803
8                      MOTOR VEHICLE THEFT     3.202254
3                       DECEPTIVE PRACTICE     2.585721
480                           INTIMIDATION     2.315964
1413509                          RITUALISM     0.000000

## Reordering Columns

In [149]:
# Move Year, Month, and Day columns after Date, then delete Date
cols = data.columns.tolist()
for col in ['Year', 'Month', 'Day', 'Time']:
    cols.remove(col)
    
date_idx = cols.index('Date')

cols.insert(date_idx + 1, 'Year')
cols.insert(date_idx + 2, 'Month')
cols.insert(date_idx + 3, 'Day')
cols.insert(date_idx + 4, 'Time')


# remove Date column from displayed columns
cols.remove('Date')
data = data[cols]

# Move Arrest Rate after Arrest
cols = data.columns.tolist()
arrest_idx = cols.index('Arrest')
cols.remove('Arrest Rate')
cols.insert(arrest_idx + 1, 'Arrest Rate')

data

,ID,Case Number,Year,Month,Day,Time,Crime Type,Location,Arrest,Arrest Rate
0,14354393,JK445985,2026,10,6,12:00 AM,CRIMINAL DAMAGE,STREET,False,3.880203
1,14350659,JK441321,2026,10,6,12:00 AM,ARSON,POLICE FACILITY / VEHICLE PARKING LOT,False,9.403311
2,14349733,JK440247,2026,10,6,12:00 AM,BURGLARY,STREET,False,4.888889
3,14350574,JK440996,2026,10,6,12:00 AM,DECEPTIVE PRACTICE,APARTMENT,False,2.585721
4,14351522,JK442283,2026,10,6,12:00 AM,CRIMINAL DAMAGE,STREET,False,3.880203
...,...,...,...,...,...,...,...,...,...,...
1603243,12470647,JE359306,2020,1,1,12:00 AM,DECEPTIVE PRACTICE,RESIDENCE,False,2.585721
1603244,12522374,JE422429,2020,1,1,12:00 AM,CRIMINAL SEXUAL ASSAULT,RESIDENCE,False,5.064958
1603245,13549608,JH368327,2020,1,1,12:00 AM,OFFENSE INVOLVING CHILDREN,RESIDENCE,False,9.554291
1603246,12578771,JE490784,2020,1,1,12:00 AM,DECEPTIVE PRACTICE,RESIDENCE,False,2.585721
1603247,12542772,JE447428,2020,1,1,12:00 AM,DECEPTIVE PRACTICE,OTHER (SPECIFY),False,2.585721

# Export Transformed Dataset

In [150]:
data.to_csv('./Crime_2020-2026.csv', index=False)